api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    title: "VGest API"
    description: "API destinée à permettre l'accès et la modification des données utilisées par VGest."
    version: 1.0.0